---
- name: AWX test playbook
  hosts: all
  become: yes
  tasks:
    - name: Ping test
      ping:

    - name: Show hostname
      command: hostname
      register: out

    - debug:
        var: out.stdout
