---
- name: Post patch validation - reboot and kernel status
  hosts: all
  gather_facts: yes
  become: yes

  tasks:

    - name: Get last reboot date
      shell: uptime -s | awk '{print $1}'
      register: last_reboot
      changed_when: false
      no_log: true

    - name: Get today's date in YYYY-MM-DD
      command: date +%F
      register: current_date
      changed_when: false
      no_log: true

    - name: Check if rebooted today
      set_fact:
        rebooted_today: "{{ last_reboot.stdout == current_date.stdout }}"
      no_log: true

    - name: Get latest kernel installation date
      shell: rpm -q --last kernel | head -n 1 | awk '{print $2, $3, $4, $5}'
      register: kernel_install
      changed_when: false
      no_log: true

    - name: Get today's date (rpm format)
      command: date '+%a %d %b %Y'
      register: today_date
      changed_when: false
      no_log: true

    - name: Check if kernel was updated today
      set_fact:
        kernel_updated_today: "{{ kernel_install.stdout == today_date.stdout }}"
      no_log: true

    - name: Packages updated today
      shell: rpm -qa --last | grep "$(date '+%a %d %b %Y')" | wc -l
      register: packages_updated
      changed_when: false

    - name: Server status - Kernel updated and server rebooted today
      debug:
        msg:
          - "✔ Server {{ inventory_hostname }} is running with latest kernel {{ ansible_kernel }} and rebooted today"
          - "✔ Total packages updated today: {{ packages_updated.stdout }}"
      when:
        - rebooted_today
        - kernel_updated_today

    - name: Server status - Kernel updated but server did not reboot
      debug:
        msg:
          - "✘ Server {{ inventory_hostname }} is running with latest kernel {{ ansible_kernel }} but did NOT reboot today"
          - "✘ Total packages updated today: {{ packages_updated.stdout }}"
      when:
        - kernel_updated_today
        - not rebooted_today

    - name: Server status - Kernel not updated and server not rebooted
      debug:
        msg:
          - "✘ Server {{ inventory_hostname }} is NOT running with latest kernel and did NOT reboot today"
          - "✘ Total packages updated today: {{ packages_updated.stdout }}"
      when:
        - not rebooted_today
        - not kernel_updated_today
